version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: "postgres:${POSTGRES_VERSION}"
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - ${POSTGRES_LOCAL_PORT:-5432}:${POSTGRES_LOCAL_PORT:-5432}
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    env_file: ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - ${PGADMIN_LOCAL_PORT}:${PGADMIN_DOCKER_PORT}
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: